config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :lists, only: %i[index create show new] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :list_id, uniqueness: { scope: :movie_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  # list = List.where('id = ?', @bookmark.list_id)

  def create
    # if @bookmark.nil?
    #   @list = List.find(params[:list_id])
    #   @movies = Movie.all
    #   @bookmark = Bookmark.new
    #   render '/lists/show'
    # end

    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list_id = @list.id
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark.movie_id = @movie.id

    if @bookmark.save
      redirect_to list_path(@list)
    else
      @movies = Movie.all
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    # @list = Movie.find(@bookmark.list_id)

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = Movie.all
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container col-6">
  <h3>Add a movie to list <%= @list.name %></h3>
  <%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :movie_id, collection: @movies.map, include_blank: false %>
  <%= f.input :comment %>
  <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= link_to "New list", new_list_path %>

<% @lists.each do |list| %>
  <h1><%= list.name %></h1>
  <%= link_to "Open list", list_path(list) %>
<% end %>

app/views/lists/new.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="container" style="text-align: center; margin-top: 50px;">
  <h2><%= @list.name %></h2>
</div>
<br>
<div class="container" style="display: flex; justify-content: space-evenly;">
  <% @list.movies.each do |movie| %>
    <div class="card" style="width: 175px; flex-direction: column; padding: 10px; text-align: center;">
      <% movie.bookmarks.each do |bookmark| %>
        <% if bookmark.list_id == @list.id %>
          <% @bmark = bookmark.id %>
        <% end %>
      <% end %>
      <%= image_tag("#{movie.poster_url}", size: "150x200") %>
      <br>
      <h4><%= movie.title %></h4>
      <p><%= movie.overview %></p>
      <%= movie.rating %>
      <%= Bookmark.find(@bmark).comment %>
      <%= link_to "Remove from list", bookmark_path(@bmark), method: :delete, data: {:confirm => 'Are you sure?'} %>
    </div>
  <% end %>
</div>
<div class="container col-6">
  <h3>Add movie to list</h3>
  <%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, include_blank: false %>
  <%= f.input :comment %>
  <%= f.submit %>
  <% end %>
</div>

<%= link_to "New bookmark", new_list_bookmark_path(@list) %>
<br>
<%= link_to "Back", lists_path %>